### ISSUE TITLE
Runtime error on startup app

### ISSUE THREAD

**Issue by Dilroop123** [hisptz/hisptz-touch#10]
Hy Team

I have cloned the repo and installed the node,cordova,ionic
cordova:  7.1.1
ionic    : 3.9.2
I get this error when i write ionic serve ...
![eroorr](https://user-images.githubusercontent.com/25072044/31437104-c1325b2c-aea1-11e7-9334-7c23da7ade83.PNG)

I HAVE ALSO TRIED ON IONIC VIEW in ios : build is successful but shows blank page.. 
please help me out..any plugin issue or something else..!!

**Comment by chingalo** [comment]
You can use stable-mobile-dev there are some instruction on how to get started with project

[dhis 2 touch stable branch](https://github.com/hisptz/hisptz-touch/blob/stable-mobile-dev/README.md)
