### ISSUE TITLE
dashboard can't open all charts

### ISSUE THREAD

**Issue by linxd** [hisptz/hisptz-touch#11]
I hava down and build the dev branch of hisptz-touch, but found dashboard module can't open all of charts, some can, some not.

**Comment by mukulu** [comment]
We're working on new build, we will address all charts supported by dhis2, feel free to enlist the charts you would like to be added also.

**Comment by chingalo** [comment]
Currently we are working to migrate all feature from interactive dashboard web app, we will keep you posted.

**Comment by linxd** [comment]
some chart can, some not ,the same type,  maybe the data or option, the chart can display in desktop dhis 2.
 and the fullscreen view is blank.

**Comment by mukulu** [comment]
We have just released first release candidate for both Android and iOS, all charts are now supported.
