### ISSUE TITLE
sync 's download metadata option can't work for program rule options.

### ISSUE THREAD

**Issue by linxd** [hisptz/hisptz-touch#23]
I have build the newest code, select all ,using sync to download data, still running,no end. ....
for program rule ,prog rule var, prog rule act ,,,

**Comment by mukulu** [comment]
Program rules have not yet been implemented, we'll keep you posted

**Comment by chingalo** [comment]
@linxd  We implemented program rules for both event capture and tracker capture modules

Currently only for non-d2 functions on the program rules

For more info just visit on https://github.com/hisptz/hisptz-touch/releases
