### ISSUE TITLE
login stopping on discrovering data store,then exit. but can login to an empty instance.

### ISSUE THREAD

**Issue by linxd** [hisptz/hisptz-touch#80]
login to dhis29(we can work in desktop version).  stop on Discovering data store (83%), after a while, exit without any sign.  but the app can login into another instance with empty database.

![image](https://user-images.githubusercontent.com/126351/51506796-0a7d7f80-1e29-11e9-961d-2c3483ec6c22.png)

**Comment by chingalo** [comment]
Hello @linxd,

There was a bug in service used to retries datastore values. But it has been resolved. 
view release note for v2.0.26 on GitHub (https://github.com/hisptz/hisptz-touch/releases/).
The updates will be available on play store later
